id: P34F7F65C
initial_creation_type: ocr
source_metadata:
  volumes:
    bf8fb14d31104364a33450595ffb921b:
      base_file: v089.txt
      image_group_id: I1PD95934
      title: འདུལ་བའི་མདོའི་འགྲེལ་པ་མངོན་པར་བརྗོད་པ་རང་གི་རྣམ་པར་བཤད་པ།
      total_pages: 1540
      volume_number: 89
