id: P34F7F65C
initial_creation_type: ocr
source_metadata:
  volumes:
    af07e81d456b4b8789829e21a5e86dba:
      base_file: v089.txt
      image_group_id: I1PD95934
      title: འདུལ་བའི་མདོའི་འགྲེལ་པ་མངོན་པར་བརྗོད་པ་རང་གི་རྣམ་པར་བཤད་པ།
      total_pages: 1540
      volume_number: 89
